### PR TITLE
AEM 6.5.12

### PR DESCRIPTION
**Pull request by stefanseifert**

### CODE REVIEW

**Comment by henrykuijpers** [comment]
@stefanseifert  Can you please release aem-dependencies 6.5.12? :)

**Comment by stefanseifert** [comment]
done - should appear on maven central in 15-30min by latest

**Comment by henrykuijpers** [comment]
@stefanseifert  Could it be that Maven Central is not completely updated yet? Or is it just slow in terms of indexing? https://search.maven.org/search?q=aem-dependencies

It still shows 6.5.11.0000 as the latest version. However, https://search.maven.org/artifact/io.wcm.maven/io.wcm.maven.aem-dependencies/6.5.12.0000/pom does work.

**Comment by stefanseifert** [comment]
it's there: https://repo1.maven.org/maven2/io/wcm/maven/io.wcm.maven.aem-dependencies/6.5.12.0000/ and that's all that matters for the actual builds maven+co.

yes, there seems to be an delay of the maven central index building. normally it's there after 4-8 hours or so, not sure why it takes that long this time. hopefully it will catch up soon.

**Pull request merged**
